# The default configuration defined in:
# https://github.com/brigade/overcommit/blob/master/config/default.yml

PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures

  TrailingWhitespace:
    enabled: true
