version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          BUNDLE_PATH: vendor/bundle
          DISABLE_SPRING: 1
          RAILS_ENV: test
          FNS_API_MASTER_KEY: test
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          REDIS_URL: redis://127.0.0.1:6379
      - image: circleci/redis:alpine
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: tt_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Update system
          command: sudo apt-get update -qq
      - run:
          name: Install necessary libs
          command: sudo apt-get install -y -qq libpq-dev cmake libzbar0
      - run:
          name: Install bundler
          command: gem install bundler:2.0.2
      - run:
          name: Which bundler?
          command: bundle -v

      # bundle cache
      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - bundle-cache-
      - run:
          name: Install gems
          command: bundle install
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Copy database.yml
          command: cp config/database-sample.yml config/database.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Restore database from schema.rb
          command: bundle exec rake db:test:prepare
      - run:
          name: Specs
          command: bundle exec rspec spec
      - run:
          name: Brakeman
          command: bundle exec brakeman
