development:
  adapter: redis
  channel_prefix: ttt_development

test:
  adapter: redis
  channel_prefix: ttt_test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: ttt_production
